baseurl = "https://dotan3.github.io/"
title = "dotan3's CTF adventures"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "dotan3"
googleAnalytics = "UA-141297077-1"
disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "dotan3"
    profile = "https://github.com/dotan3"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = ""
    description = "My description"
    github = "https://github.com/dotan3"
    # gitlab = "https://gitlab.com/XXX"
    # linkedin = "https://linkedin.com/in/XXX/"
    # gplus = "https://google.com/+XXX"
    # twitter = "https://twitter.com/XXX"
    # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    # email = "XXX@example.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

# [[menu.main]]
#     name = "Contact"
#     url = "/page/contact/"
#     weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4